### ISSUE TITLE
为什么二次封装modal要扩展不相关的其他组件

### ISSUE THREAD

**Issue by YunShangZhou** [Wxh16144/easy-antd-modal#17]

**Comment by YunShangZhou** [comment]
- 扩展的组件相对于antd有什么优势嘛。如果没有不就变相增大包体积了

**Comment by Wxh16144** [comment]
可以看看文章说的几个痛点你是否遇到过，如果没有其实完全用不着这个库，https://juejin.cn/post/7265833406226251812

**Comment by Wxh16144** [comment]
我明白你的意思了，你说的是 antd mobile 哪些内容，确实当初应该分成好几个包来做，monorepo 方式，但是后面感觉只是拓展一下，用的人可能不多，安装依赖的话可能会增加提及，但是打包项目应该会做 tree shaking 吧
